### ISSUE TITLE
Adicionar .gitignore?

### ISSUE THREAD

**Issue by tomast1337** [gioiacyberpunk/mio#1]
Talvez seria bom adicionar um arquivo .gitignore com o `auth.txt` para que ele nunca seja enviado sem querer, ou mudar o sistema de armazenamento da api key do discord

**Comment by gioiacyberpunk** [comment]
> Talvez seria bom adicionar um arquivo .gitignore com o `auth.txt` para que ele nunca seja enviado sem querer, ou mudar o sistema de armazenamento da api key do discord

O .gitignore já inclui o `auth.txt` no meu repositório local. Acredito que manter o sistema lendo o arquivo mantém simples para quem quiser rodar sua própria instância do bot. Qual outro sistema você sugere?
